apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-backend.fullname" . }}-secret
data:
  SOME_SECRET_KEY: {{ .Values.config.remoteDb.mysqlDbRootPassword }} # 'password' is encoded to base64 using `echo -n 'password' | basre64`
  # to decode the encoded value use echo -n 'cGFzc3dvcmQ=' | base64 --decode
