apiVersion: v1
kind: Pod
metadata:
  name: app-details-pod
  labels:
    app: app-details
spec:
  containers:
    - name: app-details
      image: avijit/app-details:1.0
      ports:
        - containerPort: 5000
