apiVersion: v1
kind: Service
metadata:
  name: app-details-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 5000
      nodePort: 30001
  selector:
    app: app-details
