apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-details-deploy
  labels:
    app: app-details
spec:
  template:
    metadata:
      name: app-details-pod
      labels:
        app: app-details
    spec:
      containers:
       - name: app-details
         image: avijit/app-details:1.0
         ports:
          - containerPort: 5000
         resources:
           limits:          #not overriding default requested resources
             cpu: "1"         #default value requested is 0.5 CPU
             memory: 1Gi    #default value requested is 256Mi
           requests:
             cpu: 100m      #default value requested is 0.5 CPU
  replicas: 3
  selector:
    matchLabels:
      app: app-details
