name: Python application

on:
  push:
    paths-ignore:
       - '**.md'
    pull_request:
       - '**.md'

jobs:
  build:
    name: Run Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install dependencies
      working-directory: ./opencv
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt
    - name: Lint with numpy
      working-directory: ./opencv
      run: |
        pip install numpy
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with opencv-python
      working-directory: ./opencv
      run: |
        pip install opencv-python
        
    - name: pytest
      working-directory: ./opencv
      run: |
        pip install pytest
        pytest
